name: Backend Continuous Integration

on:
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    name: Build Node.js
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Run test
        run: npm test
