name: Backend Continuous Integration

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
      uses: actions/setup-node@v3.4.0

      - name: Install dependencies
        run: npm ci

      - name: Run test
        run: npm test
